### ISSUE TITLE
Trying to scrape within a time period, but results are coming from time period outside my specified range!

### ISSUE THREAD

**Issue by das00015** [Altimis/Scweet#110]
---
```
query = "Gap AND #endviolence"
data = scrape(words=[query], since="2019-09-09", until="2019-09-19", from_account = None,interval=1, 
      headless=True, display_type="Top", save_images=False, proxy = None, save_dir = 'outputs',
             resume=False, filter_replies=True, proximity=False)
```
---
You can see the results are returning tweets from 2022.
--
```
Scraping on headless mode.
looking for tweets between 2019-09-09 and 2019-09-10 ...
 path : https://twitter.com/search?q=(Gap AND #endviolence)%20until%3A2019-09-10%20since%3A2019-09-09%20%20-filter%3Areplies&src=typed_query
Tweet made at: 2022-02-10T16:46:25.000Z is found.
Tweet made at: 2022-02-11T04:00:54.000Z is found.
Tweet made at: 2022-02-11T02:52:24.000Z is found.
Tweet made at: 2022-02-10T16:32:08.000Z is found.
```
---
How do I get the tweets in the right time period? It looks like it is taking from a since date to most recent. The until parameter is not getting recognized ?

**Comment by Altimis** [comment]
Actually the problem comes from your query. You need to add each word of your query to the list as an element, and not in the same string splited by AND. You can enter the link showed in the result and you will see that Twitter doesnt take into account time period and other arguments after adding AND word in the query. The link : https://twitter.com/search?q=(Gap AND #endviolence)%20until%3A2019-09-10%20since%3A2019-09-09%20%20-filter%3Areplies&src=typed_query

**Comment by das00015** [comment]
Was able to understand the issue : the specific query I was looking for was the phrase "ben&jerrys", this triggers a different query and breaks the data collection, because of the and operator which is present in it.
