### ISSUE TITLE
Thanks for you work!

### ISSUE THREAD

**Issue by ZouTaooo** [Altimis/Scweet#8]
I want to know what's the meaning of **to account** and **from account**.
And how can i get a tweeter user's tweet including text and the link of picture and video.
Thanks again!

**Comment by Altimis** [comment]
Hi @ZouTaooo, Thank you.
to_account means : scrap tweets posted in response to "to_account" account.
from_account means : scrap tweets posted by "from_account" account. 

Suppose you want to get @Twitter's tweets, you need to specify the ``from_account`` argument as : ``--from_account Twitter`` (you also need to specify the ``start_date`` and ``max_date`` arguments. 
I just updated the code so that you can scrap images links. Please try it and keep me updated.

**Comment by ZouTaooo** [comment]
I am sorry, I can't scrape anything from the below command
I am in China, when I use proxy I can't open twitter in laptop browser, but I can open it on phone. 
I don't know where is my flaw.

python scweet.py --from_account "IGN" --max_date 2020-01-05 --start_date 2020-01-01
 --limit 10 --interval 1 --navig chrome --display_type Latest --lang="en" --headless True

![MK(O(F4XR6A9WLXW`GICM}7](https://user-images.githubusercontent.com/28475389/103121058-6906a480-46b5-11eb-9659-ab006862ad01.png)

**Comment by Altimis** [comment]
Hi again @ZouTaooo. I just tried the same command as yours and it worked for me : 
![image](https://user-images.githubusercontent.com/48790841/103121264-b8c87a00-467b-11eb-9093-6d9fe8db0d60.png)
I think the problem is from the proxy. How do you use twitter in your location ? if you are using poxy, you can simply specify your proxy with the ``--proxy`` argument and it will work.

**Comment by ZouTaooo** [comment]
Thanks again!
 I already read your code, and I find if you want to write chinese into csv file you need to set the encoding = 'utf-8-sig',or it cause the csv file would be wrong when you use excel to open it. Just remind other people who stuck with the problem.

Your work help me a lot. Thanks!
![@H5SO30J8S4)49{(3R1T9ZG](https://user-images.githubusercontent.com/28475389/103135118-10ed9380-46f1-11eb-829a-f4b3006076f1.png)
