### ISSUE TITLE
Can you explain every parameter in the function `scrap`?

### ISSUE THREAD

**Issue by belalhamdy** [Altimis/Scweet#82]
I need to know every parameter usage in the function scrap which is 
```python
scrape(since, until=None, words=None, to_account=None, from_account=None, mention_account=None, interval=5, lang=None,
          headless=True, limit=float("inf"), display_type="Top", resume=False, proxy=None, hashtag=None, 
          show_images=False, save_images=False, save_dir="outputs", filter_replies=False, proximity=False)
```
Can you explain it please?

**Comment by Altimis** [comment]
This function scrapes data from date `since` until date `until` according to list of words `words`. You can also scrape data according to `to_account` (which are the tweets published to this account), `from_account` (which are tweets  published from this account), `hashtag` or `mention_account`. 
Use `headless` to scrape data with headless chrome. Use limit to `limit` the number of tweets to be scraped. Set `display_type` to "Top" if you want to scrape only top tweets or "Latest" to scrape all tweets. Use `resume` to resume the latest scraping work. Use proxy if you want to set a proxy to chrome for selenium. If yo want to save images use save_images. USe save_dir to save the outputs. Use filter_repliers to filter the repliers to tweets in order to scrape only the main tweets.

**Comment by belalhamdy** [comment]
@Altimis  thanks for your reply.. I do not get the usage of `headless` parameter what will happen if I used it or not?

**Comment by Altimis** [comment]
> @Altimis thanks for your reply.. I do not get the usage of `headless` parameter what will happen if I used it or not?

Did you try it to see yourself ? True means that you scrape with headless chrome window (you don't get to see the process of scraping).

**Comment by belalhamdy** [comment]
Thanks

> > @Altimis thanks for your reply.. I do not get the usage of `headless` parameter what will happen if I used it or not?
> 
> Did you try it to see yourself ? True means that you scrape with headless chrome window (you don't get to see the process of scraping).

Thanks
