### ISSUE TITLE
Request add new feature

### ISSUE THREAD

**Issue by okkymabruri** [Altimis/Scweet#9]
Change the data features
- [x] UserName -> UserScreenName
- [x] Handle -> UserName

The below may be useful for some users. Add a feature that can retrieve from tweets
- [x] tweet-url

User information
- [ ] date user joined
- [ ] user no. of following
- [ ] user no. of followers
- [ ] user is verified?

**Comment by Altimis** [comment]
Hi again @okkymabruri. Thank you for your feedback.
I added the tweet_url feature to the csv file. Regarding the user information, I'm afraid that those informations could be retrieved only if the ``from_account`` argument were given. Because it would be a time consuming task if the script has to retrieve user information for every tweet scraped.

**Comment by okkymabruri** [comment]
Okay, thanks. I think you're right. It needs more time to retrieve user information.
Actually, I need user information. but it's okay

**Comment by Altimis** [comment]
@okkymabruri If you are talking about retrieving followings followers ... for a specific user, I'm still working on it. But as you know, it's gonna be a big challenge for Scweet to retrieve user's information for every tweet scraped.

**Comment by okkymabruri** [comment]
> @okkymabruri If you are talking about retrieving followings followers ... for a specific user, I'm still working on it. But as you know, it's gonna be a big challenge for Scweet to retrieve user's information for every tweet scraped.

Sure. Thanks for it
